apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-tools
  namespace: default
imagePullSecrets:
  - name: gitlab-creds
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: modify-nodes-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-tools-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: modify-nodes-role
subjects:
  - kind: ServiceAccount
    name: k8s-tools
    namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: node-tainter
  namespace: default
  labels:
    type: cronjob
    tech: shell
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: k8s-tools
              image: registry.gitlab.com/datacue.co/k8s-tools
          restartPolicy: OnFailure
          serviceAccountName: k8s-tools
