apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-tools
  namespace: default
imagePullSecrets:
  - name: gitlab-creds
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: modify-nodes-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-tools-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: modify-nodes-role
subjects:
  - kind: ServiceAccount
    name: k8s-tools
    namespace: default
